name: Boas-vindas Ajustado

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  boas-vindas:
    runs-on: ubuntu-latest
    steps:
      - name: Cumprimentar a turma
        run: echo "Olá, GitHub Actions!"
      - name: Listar Arquivos
        run: ls -la